// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RollerMillMonitor.Data;

#nullable disable

namespace RollerMillMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005064149_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("RollerMillMonitor.Models.AlarmRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AckBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AckTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AlarmTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AlarmValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlcId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecoveryTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Threshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "AlarmTime");

                    b.HasIndex("PointId", "AlarmType", "IsActive");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("RollerMillMonitor.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RollerMillMonitor.Models.Plc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Plcs");
                });

            modelBuilder.Entity("RollerMillMonitor.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AlarmDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlarmEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Deadband")
                        .HasColumnType("REAL");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("High")
                        .HasColumnType("REAL");

                    b.Property<double?>("HighHigh")
                        .HasColumnType("REAL");

                    b.Property<double?>("Low")
                        .HasColumnType("REAL");

                    b.Property<double?>("LowLow")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Offset")
                        .HasColumnType("REAL");

                    b.Property<int?>("PlcId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecoveryDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Scale")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlcId");

                    b.HasIndex("DeviceId", "Name");

                    b.HasIndex("DeviceId", "PlcId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("RollerMillMonitor.Models.TrendRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PointId", "Timestamp");

                    b.ToTable("Trends");
                });

            modelBuilder.Entity("RollerMillMonitor.Models.AlarmRecord", b =>
                {
                    b.HasOne("RollerMillMonitor.Models.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("RollerMillMonitor.Models.Point", b =>
                {
                    b.HasOne("RollerMillMonitor.Models.Device", "Device")
                        .WithMany("Points")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RollerMillMonitor.Models.Plc", "Plc")
                        .WithMany()
                        .HasForeignKey("PlcId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("Plc");
                });

            modelBuilder.Entity("RollerMillMonitor.Models.TrendRecord", b =>
                {
                    b.HasOne("RollerMillMonitor.Models.Point", null)
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RollerMillMonitor.Models.Device", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
